import Foundation
import XCTest
@testable import WorldClockCore

// Golden vectors generated by scripts/export-shared.mjs from the real JS (shared/golden.json, copied into
// Tests/WorldClockCoreTests/Resources by sync-resources.mjs). Every vector of every section is checked.

struct Golden: Decodable {
    struct Meta: Decodable { var node: String?; var icu: String?; var tz: String? }
    struct Offset: Decodable { var zone: String; var epochMs: Double; var offsetMinutes: Int; var formatted: String }
    struct Zoned: Decodable { var zone: String; var y: Int; var m: Int; var d: Int; var h: Int; var mi: Int; var epochMs: Double; var note: String }
    struct DayDiff: Decodable { var zone: String; var refZone: String; var epochMs: Double; var diff: Int }
    struct RelLabel: Decodable { var zone: String; var localZone: String; var epochMs: Double; var label: String? }
    struct ParseTimeV: Decodable { var input: String; var result: [Int]? }
    struct InputText: Decodable { var h: Int; var m: Int; var hour12: Bool; var text: String }
    struct PhaseOfV: Decodable { var hour: Int; var phase: String }
    struct SunTimesV: Decodable { var name: String; var lat: Double; var lng: Double; var epochMs: Double; var sunriseMs: Double?; var sunsetMs: Double?; var polar: String? }
    struct SunAltitude: Decodable { var lat: Double; var lng: Double; var epochMs: Double; var altitude: Double }
    struct SunPhaseV: Decodable { var lat: Double; var lng: Double; var epochMs: Double; var localHour: Int; var phase: String }
    struct SkyPhaseV: Decodable { var lat: Double; var lng: Double; var epochMs: Double; var phase: String; var night: Bool? }
    struct IsWorkingV: Decodable { var zone: String; var hours: WorkingHours; var epochMs: Double; var working: Bool }
    struct PlannerV: Decodable {
        var name: String; var source: String; var y: Int; var m: Int; var d: Int; var zones: [String]
        var hours: [String: WorkingHours]; var columnsMs: [Double]; var cells: [String: [String]]
        var localTimes: [String: [[Int]]]?; var runs: [[Int]]; var totalHours: Int; var best: [Int]?
    }
    struct NextChange: Decodable {
        struct R: Decodable { var atMs: Double; var delta: Int; var old: Int }
        var zone: String; var epochMs: Double; var result: R?
    }
    struct DstNote: Decodable { var zone: String; var epochMs: Double; var daysUntil: Int?; var delta: String?; var text: String? }
    struct OffsetQuery: Decodable { var input: String; var minutes: Int? }
    struct SearchV: Decodable {
        var query: String; var lang: String?; var nowMs: Double; var excluding: [String]; var mustInclude: [String]
        var mustExclude: [String]?; var first: String?; var firstReliable: Bool?; var kind: String
    }
    struct CityNameV: Decodable { var zone: String; var lang: String; var city: String }
    struct CountryV: Decodable { var zone: String; var lang: String; var country: String }
    struct CanonicalV: Decodable { var zone: String; var canonical: String }
    struct LanguageResolveV: Decodable { var preferred: [String]; var lang: String }
    struct TemplateV: Decodable { var template: String; var vars: [String: String]; var result: String }
    struct MapV: Decodable {
        struct Sample: Decodable { var lat: Double; var lng: Double; var altitude: Double; var isNight: Bool; var nightAlpha: Double? }
        struct Term: Decodable { var lng: Double; var lat: Double }
        var epochMs: Double; var subsolar: Coordinate; var samples: [Sample]; var terminator: [Term]
    }
    struct MapConstants: Decodable {
        struct Wrap: Decodable { var lng: Double; var wrapped: Double }
        struct Alpha: Decodable { var altitude: Double; var alpha: Double }
        var sunsetAltitude: Double; var wrapLng: [Wrap]; var nightAlpha: [Alpha]
    }

    var meta: Meta
    var offsets: [Offset]
    var zonedToEpoch: [Zoned]
    var dayDiff: [DayDiff]
    var relLabel: [RelLabel]
    var parseTime: [ParseTimeV]
    var inputText: [InputText]
    var phaseOf: [PhaseOfV]
    var sunTimes: [SunTimesV]
    var sunAltitude: [SunAltitude]
    var sunPhase: [SunPhaseV]
    var skyPhase: [SkyPhaseV]
    var isWorking: [IsWorkingV]
    var planner: [PlannerV]
    var nextOffsetChange: [NextChange]
    var dstNote: [DstNote]
    var dstTemplates: [String: String]
    var parseOffsetQuery: [OffsetQuery]
    var search: [SearchV]
    var cityName: [CityNameV]
    var country: [CountryV]
    var canonical: [CanonicalV]
    var languageResolve: [LanguageResolveV]
    var template: [TemplateV]
    var map: [MapV]
    var mapConstants: MapConstants?

    static let shared: Golden = {
        let url = Bundle.module.url(forResource: "golden", withExtension: "json")!
        return try! JSONDecoder().decode(Golden.self, from: Data(contentsOf: url))
    }()
}

/// Vectors skipped because this OS's tzdata differs from the Node/ICU build that generated golden.json
/// (see meta.tz). Keys are "section|zone|epochMs". Keep EMPTY unless a tzdata-version difference is proven.
let tzdataAllowList: Set<String> = []

private func date(_ ms: Double) -> Date { Date(timeIntervalSince1970: ms / 1000) }
private func ms(_ d: Date) -> Double { (d.timeIntervalSince1970 * 1000).rounded() }

final class GoldenTests: XCTestCase {
    let g = Golden.shared

    func testMetaAndCounts() {
        XCTAssertFalse(g.offsets.isEmpty)
        XCTAssertFalse(g.search.isEmpty)
        print("golden generated with node \(g.meta.node ?? "?") icu \(g.meta.icu ?? "?") tz \(g.meta.tz ?? "?")")
    }

    func testOffsets() {
        for v in g.offsets where !tzdataAllowList.contains("offsets|\(v.zone)|\(Int64(v.epochMs))") {
            XCTAssertEqual(TimeMath.offsetMinutes(v.zone, at: date(v.epochMs)), v.offsetMinutes, "\(v.zone) @\(v.epochMs)")
            XCTAssertEqual(TimeMath.formatOffset(v.offsetMinutes), v.formatted)
        }
    }

    func testZonedToEpoch() {
        for v in g.zonedToEpoch where !tzdataAllowList.contains("zonedToEpoch|\(v.zone)|\(Int64(v.epochMs))") {
            let d = TimeMath.zonedToEpoch(v.zone, year: v.y, month: v.m, day: v.d, hour: v.h, minute: v.mi)
            XCTAssertEqual(ms(d), v.epochMs, "\(v.zone) \(v.y)-\(v.m)-\(v.d) \(v.h):\(v.mi) (\(v.note))")
        }
    }

    func testDayDiff() {
        for v in g.dayDiff {
            XCTAssertEqual(TimeMath.dayDiff(v.zone, at: date(v.epochMs), relativeTo: v.refZone), v.diff, "\(v.zone) vs \(v.refZone) @\(v.epochMs)")
        }
    }

    func testRelLabel() {
        for v in g.relLabel {
            XCTAssertEqual(TimeMath.relativeOffsetLabel(v.zone, at: date(v.epochMs), localZone: v.localZone), v.label, "\(v.zone) vs \(v.localZone)")
        }
    }

    func testParseTime() {
        for v in g.parseTime {
            let r = ParseTime.parse(v.input)
            XCTAssertEqual(r.map { [$0.hour, $0.minute] }, v.result, "parseTime(\"\(v.input)\")")
        }
    }

    func testInputText() {
        for v in g.inputText {
            XCTAssertEqual(ParseTime.inputText(HourMinute(hour: v.h, minute: v.m), hour12: v.hour12), v.text)
        }
    }

    func testPhaseOf() {
        for v in g.phaseOf { XCTAssertEqual(TimeMath.phaseOf(hour: v.hour).rawValue, v.phase, "hour \(v.hour)") }
    }

    func testSunTimes() {
        for v in g.sunTimes {
            let t = Sun.times(at: date(v.epochMs), lat: v.lat, lng: v.lng)
            XCTAssertEqual(t.polar?.rawValue, v.polar, v.name)
            XCTAssertEqual(t.sunrise == nil, v.sunriseMs == nil, v.name)
            XCTAssertEqual(t.sunset == nil, v.sunsetMs == nil, v.name)
            if let a = t.sunrise, let b = v.sunriseMs { XCTAssertEqual(ms(a), b, accuracy: 60_000, "sunrise " + v.name) }
            if let a = t.sunset, let b = v.sunsetMs { XCTAssertEqual(ms(a), b, accuracy: 60_000, "sunset " + v.name) }
        }
    }

    func testSunAltitude() {
        for v in g.sunAltitude {
            XCTAssertEqual(Sun.altitude(at: date(v.epochMs), lat: v.lat, lng: v.lng), v.altitude, accuracy: 0.01)
        }
    }

    func testSunPhase() {
        for v in g.sunPhase {
            let p = Sun.phase(at: date(v.epochMs), coordinate: Coordinate(lat: v.lat, lng: v.lng), localHour: v.localHour)
            XCTAssertEqual(p.rawValue, v.phase, "\(v.lat),\(v.lng) @\(v.epochMs) h\(v.localHour)")
        }
    }

    func testSkyPhase() {
        for v in g.skyPhase {
            let d = date(v.epochMs)
            if let night = v.night { XCTAssertEqual(!Sun.isDay(at: d, lat: v.lat, lng: v.lng), night) }
            XCTAssertEqual(Sky.phase(at: d, coordinate: Coordinate(lat: v.lat, lng: v.lng)).rawValue, v.phase, "\(v.lat),\(v.lng) @\(v.epochMs)")
        }
    }

    func testIsWorking() {
        for v in g.isWorking {
            let h = Planner.hours(for: v.zone, in: [v.zone: v.hours])
            XCTAssertEqual(Planner.isWorking(v.zone, hours: h, at: date(v.epochMs)), v.working, "\(v.zone) \(v.hours) @\(v.epochMs)")
        }
    }

    func testPlanner() {
        for v in g.planner {
            let r = Planner.plan(source: v.source, year: v.y, month: v.m, day: v.d, zones: v.zones, hours: v.hours)
            XCTAssertEqual(r.columns.map(ms), v.columnsMs, v.name)
            XCTAssertEqual(r.rows.map(\.zone), v.zones, v.name)
            for row in r.rows {
                XCTAssertEqual(row.cells.map(\.rawValue), v.cells[row.zone], "\(v.name): \(row.zone)")
                if let lt = v.localTimes?[row.zone] {
                    XCTAssertEqual(row.localTimes.map { [$0.hour, $0.minute] }, lt, "\(v.name): \(row.zone) local times")
                }
            }
            XCTAssertEqual(r.runs.map { [$0.start, $0.end] }, v.runs, v.name)
            XCTAssertEqual(r.totalHours, v.totalHours, v.name)
            XCTAssertEqual(r.best.map { [$0.start, $0.end] }, v.best, v.name)
        }
    }

    func testNextOffsetChange() {
        for v in g.nextOffsetChange {
            let r = ClockChanges.nextOffsetChange(v.zone, after: date(v.epochMs))
            XCTAssertEqual(r == nil, v.result == nil, "\(v.zone) @\(v.epochMs)")
            if let r, let e = v.result {
                XCTAssertEqual(ms(r.at), e.atMs, "\(v.zone) @\(v.epochMs)")
                XCTAssertEqual(r.deltaMinutes, e.delta)
                XCTAssertEqual(r.oldOffsetMinutes, e.old)
                // wall time in the old offset
                let wall = e.atMs + Double(e.old) * 60_000
                let sod = Int(((wall / 1000).truncatingRemainder(dividingBy: 86400) + 86400).truncatingRemainder(dividingBy: 86400))
                XCTAssertEqual(r.wallClockBefore, HourMinute(hour: sod / 3600, minute: (sod % 3600) / 60))
            }
        }
    }

    func testDstNote() throws {
        XCTAssertEqual(Set(g.dstTemplates.keys), ["dst.today", "dst.tomorrow", "dst.in"])
        for v in g.dstNote {
            let msg = "\(v.zone) @\(v.epochMs)"
            let note = ClockChanges.note(v.zone, at: date(v.epochMs))
            XCTAssertEqual(note?.daysUntil, v.daysUntil, msg)
            XCTAssertEqual(note == nil, v.text == nil, msg)
            guard let note, let text = v.text else { continue }
            XCTAssertEqual(ClockChanges.deltaText(note.change.deltaMinutes), v.delta, msg)
            let template = try XCTUnwrap(g.dstTemplates[note.textKey], msg)
            XCTAssertEqual(Template.fill(template, note.textVars), text, msg)
        }
    }

    func testParseOffsetQuery() {
        for v in g.parseOffsetQuery {
            XCTAssertEqual(Search.parseOffsetQuery(v.input), v.minutes, "parseOffsetQuery(\"\(v.input)\")")
        }
    }

    func testSearch() throws {
        for v in g.search {
            let lang = try XCTUnwrap(AppLanguage(rawValue: v.lang ?? "en"))
            let r = Search.search(v.query, excluding: Set(v.excluding), now: date(v.nowMs), language: lang)
            let msg = "search(\"\(v.query)\", \(lang)) -> \(r.zones)"
            for z in v.mustInclude { XCTAssertTrue(r.zones.contains(z), "\(msg) missing \(z)") }
            for z in v.excluding + (v.mustExclude ?? []) { XCTAssertFalse(r.zones.contains(z), "\(msg) contains excluded \(z)") }
            if v.firstReliable ?? true { XCTAssertEqual(r.zones.first, v.first, msg) }
            switch (r.kind, v.kind) {
            case (.text, "text"), (.abbreviation, "abbreviation"): break
            case (.offset(let m), "offset"): XCTAssertEqual(m, Search.parseOffsetQuery(Search.fold(v.query.trimmingCharacters(in: .whitespaces))), msg)
            default: XCTFail("\(msg): kind \(r.kind) != \(v.kind)")
            }
        }
    }

    func testCityName() throws {
        for v in g.cityName {
            let lang = try XCTUnwrap(AppLanguage(rawValue: v.lang))
            XCTAssertEqual(ZoneCatalog.shared.cityName(of: v.zone, language: lang), v.city, "\(v.zone) (\(v.lang))")
            if v.lang == "en" { XCTAssertEqual(ZoneCatalog.shared.cityName(of: v.zone), v.city, v.zone) }
        }
    }

    func testCountry() throws {
        for v in g.country {
            let lang = try XCTUnwrap(AppLanguage(rawValue: v.lang))
            XCTAssertEqual(ZoneCatalog.shared.country(of: v.zone, language: lang), v.country, "\(v.zone) (\(v.lang))")
        }
    }

    func testCanonical() {
        for v in g.canonical { XCTAssertEqual(ZoneCatalog.shared.canonical(v.zone), v.canonical, v.zone) }
    }

    func testLanguageResolve() {
        for v in g.languageResolve {
            XCTAssertEqual(AppLanguage.resolve(.auto, preferred: v.preferred).rawValue, v.lang, "\(v.preferred)")
        }
    }

    func testTemplate() {
        for v in g.template { XCTAssertEqual(Template.fill(v.template, v.vars), v.result, v.template) }
    }

    func testMap() {
        for v in g.map {
            let d = date(v.epochMs)
            let ss = WorldMap.subsolar(at: d)
            XCTAssertEqual(ss.lat, v.subsolar.lat, accuracy: 0.01)
            XCTAssertEqual(ss.lng, v.subsolar.lng, accuracy: 0.01)
            for s in v.samples {
                XCTAssertEqual(WorldMap.altitude(lat: s.lat, lng: s.lng, subsolar: ss), s.altitude, accuracy: 0.01, "\(s.lat),\(s.lng)")
                XCTAssertEqual(WorldMap.isNight(at: d, lat: s.lat, lng: s.lng), s.isNight, "\(s.lat),\(s.lng)")
                if let a = s.nightAlpha {
                    XCTAssertEqual(WorldMap.nightAlpha(altitude: WorldMap.altitude(lat: s.lat, lng: s.lng, subsolar: ss)), a, accuracy: 0.01)
                }
            }
            for t in v.terminator {
                XCTAssertEqual(WorldMap.terminatorLat(lng: t.lng, subsolar: ss), t.lat, accuracy: 0.01, "terminator \(t.lng)")
            }
        }
    }

    func testMapConstants() throws {
        let c = try XCTUnwrap(g.mapConstants)
        XCTAssertEqual(WorldMap.sunsetAltitude, c.sunsetAltitude)
        for w in c.wrapLng { XCTAssertEqual(WorldMap.wrapLng(w.lng), w.wrapped, accuracy: 1e-9, "wrapLng(\(w.lng))") }
        for a in c.nightAlpha { XCTAssertEqual(WorldMap.nightAlpha(altitude: a.altitude), a.alpha, accuracy: 1e-9, "nightAlpha(\(a.altitude))") }
    }
}
